import AdminNavbar from "./components/admin-navbar"
import "../(front)/globals.css";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-1  flex-col">
          <AdminNavbar />
          <div className="w-4/12">
          </div>
          <div className="w-8/12">
            {children}
          </div>



        </div>


      </body>
    </html>
  )
}
