import AdminNavbar from "./components/admin-navbar"
import "../(front)/globals.css";
import Sidebar from "./components/sidebar";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-1  flex-col">
          <AdminNavbar />
          <div className="flex flex-1  ">
            <div className="w-2/12 ">
              <Sidebar />
            </div>
            <div className="w-10/12">
              {children}
            </div>
          </div>




        </div>


      </body>
    </html>
  )
}
